version: '3'
services: 
  app: 
    container_name: forgetsy_reviews
    restart: always
    build: .
    ports: 
      - '80:3004'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'